### ISSUE TITLE
How to run spark job on yarn with different user

### ISSUE THREAD

**Issue by Guru107** [saurfang/sbt-spark-submit#12]
Currently, I am facing an issue where the plugin is unable to submit the job because of user permission. Is there any environment variable which will change the user?

**Comment by saurfang** [comment]
That really depends on what authentication system your hadoop cluster uses. If there is no authentication middleware in place, `--proxy-user` might be what you can use. See command line options section in https://jaceklaskowski.gitbooks.io/mastering-apache-spark/spark-submit.html
