### ISSUE TITLE
Change spark log-level

### ISSUE THREAD

**Issue by ghost** [saurfang/sbt-spark-submit#2]
Hi,

Normally I change the spark log-level in $SPARK_HOME/conf/log4js.properties. I'd like to put the log-level to WARN but I don't know how to change it when I use this plugin.

**Comment by saurfang** [comment]
I have been putting `log4j.properties` either in the jar such as under `src/main/resources` or directly on the classpath. Either way it can be picked up correctly by Spark. 

Occasionally I have troubles with log4j if I add extra classpath entries on the driver and executors, there I am able to get it working by specifying a custom log4j file name as described in http://stackoverflow.com/questions/1140358/how-to-initialize-log4j-properly
