### ISSUE TITLE
 ERROR ContextCleaner: Error in cleaning thread

### ISSUE THREAD

**Issue by smartres** [saurfang/sbt-spark-submit#8]
Hi!
I have a program with Spark-scala, I created a self-contained application with SBT.
The principal idea for my project is to cretae a system of recommendation. When I run it by sbt run it genere an error:

Not enough arguments received.
16/12/07 14:11:16 ERROR ContextCleaner: Error in cleaning thread
java.lang.InterruptedException
at java.lang.Object.wait(Native Method)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"

But the end of running it display success, I can't understannd, it's a wrong in my code or another problem?
I tried to run it on command-line by lunching spark-shell, it run fine and i can show my result of prediction and test.

Can you answers me please!

**Comment by saurfang** [comment]
Can you show me exact step you use to launch it in sbt and in spark-shell respectively?

**Comment by smartres** [comment]
Hello,

I resolved it, but now when i run my project, it do not show me any result, this is the steps:
I open the folder of my project, then i write this command:
# cd projectFilm
# sbt compile
#sbt run
#sbt package

This is following my messages of running:

[root@sandbox projectFilms]# sbt compile
[info] Set current project to system of recommandation (in build file:/root/projectFilms/)
[success] Total time: 6 s, completed Jan 15, 2017 12:41:25 PM
[root@sandbox projectFilms]# sbt run
[info] Set current project to system of recommandation (in build file:/root/projectFilms/)
[info] Running appFilms 
[success] Total time: 7 s, completed Jan 15, 2017 12:42:31 PM
[root@sandbox projectFilms]# sbt package
[info] Set current project to system of recommandation (in build file:/root/projectFilms/)
[success] Total time: 4 s, completed Jan 15, 2017 12:42:50 PM
[root@sandbox projectFilms]# spark-submit --class "appFilms" --master local[4] target/scala-2.11/system-of-recommandation_2.11-1.0.jar 
[root@sandbox projectFilms]# 

But now it do not  show me any result, may the problem, because i separated my dataset on 3 parties by accross validation (train, validation and test), i find all my data in the train but the validation and the test are empty.

And when I launch my spark-shell to run by each ligne of my code, also i can't find my data as i like.
I can't publish my code here ?

Thank you for your answer and your help.

**Comment by saurfang** [comment]
Great. As this now has little to do with the plugin, it is more suitable for stackoverflow. I suggest you post over there. You can add more logging to your program to find out which step caused lack of result. If you mean the command literally has zero printout, then you should check your log4j configuration.
